name: Testing suite
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t vim-tpipeline -f tests/Dockerfile .
    - name: Check help tags
      run: docker run -w /tmp/vim-tpipeline -t vim-tpipeline scripts/check-helptags.sh
    - name: Run tests with vim
      run: docker run -it vim-tpipeline make tests_vim
    - name: Run tests with neovim
      run: docker run -it vim-tpipeline make tests_neovim
