name: Testing suite
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t vim-tpipeline -f tests/Dockerfile .
    - name: Run the Docker image
      run: docker run -it vim-tpipeline
